import Head from 'next/head'
import Welcome from '../components/Welcome/Welcome'
import { getToken, getUser, resetUserSession, setUserSession } from '../sevice/AuthService';
import { useEffect, useState } from 'react'
import axios from 'axios';
import Profile from './profile'
import Router from 'next/router';

const verifyTokenAPIURL = 'https://0e4l76puj4.execute-api.eu-central-1.amazonaws.com/prod-sardor-test/verify';

export default function Home() {
  const [isAuthenicating, setAuthenicating] = useState(true);

  useEffect(() => {
    const token = getToken();
    if (token === 'undefined' || token === undefined || token === null || !token) {
      return;
    }

    const requestConfig = {
      headers: {
        'x-api-key': 'WzMb4C91LO2lNTxgncDAm18iHYMteA6t7ikI36oT'
      }
    }
    const requestBody = {
      user: getUser(),
      token: token
    }

    axios.post(verifyTokenAPIURL, requestBody, requestConfig).then(response => {
      setUserSession(response.data.user, response.data.token);
      setAuthenicating(false);
    }).catch(() => {
      resetUserSession();
      setAuthenicating(false);
    })
  }, []);

  const token = getToken();
  if (isAuthenicating && token) {
    return <div className="content">Authenicating...</div>
  }

  if (isAuthenicating === false) {
    Router.push('/profile')
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isAuthenicating && <Welcome />}
    </>
  )
}
